CREATE TABLE IF NOT EXISTS users (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text,
  email text NOT NULL UNIQUE,
  role text NOT NULL CHECK (role IN ('admin', 'user')),
  password_hash text,
  created_at timestamptz NOT NULL DEFAULT now(),
  last_login_at timestamptz,
  deleted_at timestamptz
);

CREATE TABLE IF NOT EXISTS students (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome_completo text NOT NULL,
  data_nascimento date,
  idade integer,
  naturalidade text,
  raca_cor text,
  sexo text,
  rg text,
  cpf text,
  nis text,
  certidao_termo text,
  certidao_folha text,
  certidao_livro text,
  endereco_cep text,
  endereco_logradouro text,
  endereco_numero text,
  endereco_complemento text,
  endereco_bairro text,
  endereco_cidade text,
  endereco_uf text,
  nome_pai text,
  nome_mae text,
  cras_referencia text,
  estado_civil_pais text,
  contato_conjuge_nome text,
  contato_conjuge_telefone text,
  tipo_domicilio text,
  renda_familiar text,
  escola_nome text,
  escola_serie text,
  escola_ano text,
  escola_professor text,
  escola_periodo text,
  historico_escolar text,
  ubs_referencia text,
  tem_problema_saude boolean NOT NULL DEFAULT false,
  problema_saude_descricao text,
  tem_restricoes boolean NOT NULL DEFAULT false,
  restricoes_descricao text,
  usa_medicamentos boolean NOT NULL DEFAULT false,
  medicamentos_descricao text,
  tem_alergias boolean NOT NULL DEFAULT false,
  alergias_descricao text,
  acompanhamentos text,
  tem_deficiencia boolean NOT NULL DEFAULT false,
  deficiencia_descricao text,
  tem_supervisao boolean NOT NULL DEFAULT false,
  supervisao_descricao text,
  atividades_extras text,
  termo_responsabilidade boolean NOT NULL DEFAULT false,
  autorizacao_imagem boolean NOT NULL DEFAULT false,
  autorizacao_saida text CHECK (autorizacao_saida IN ('sim', 'nao', 'somente-com-responsavel')),
  created_at timestamptz NOT NULL DEFAULT now(),
  created_by_user_id bigint REFERENCES users(id),
  created_by_email text NOT NULL,
  updated_at timestamptz NOT NULL DEFAULT now(),
  updated_by_user_id bigint REFERENCES users(id),
  updated_by_email text NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_students_cpf ON students (cpf);
CREATE INDEX IF NOT EXISTS idx_students_nome_completo ON students (nome_completo);
CREATE INDEX IF NOT EXISTS idx_students_escola_nome ON students (escola_nome);
CREATE INDEX IF NOT EXISTS idx_students_created_by_email ON students (created_by_email);
CREATE INDEX IF NOT EXISTS idx_students_updated_by_email ON students (updated_by_email);

CREATE TABLE IF NOT EXISTS student_responsaveis_legais (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id bigint NOT NULL REFERENCES students(id) ON DELETE CASCADE,
  posicao smallint NOT NULL CHECK (posicao IN (1, 2)),
  nome text,
  data_nascimento date,
  rg text,
  cpf text,
  celular text,
  operadora text,
  whatsapp text,
  fixo text,
  parentesco text,
  UNIQUE (student_id, posicao)
);

CREATE TABLE IF NOT EXISTS student_membros_familiares (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id bigint NOT NULL REFERENCES students(id) ON DELETE CASCADE,
  nome text,
  parentesco text,
  profissao text,
  renda text
);

CREATE TABLE IF NOT EXISTS student_pessoas_autorizadas (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id bigint NOT NULL REFERENCES students(id) ON DELETE CASCADE,
  nome text,
  documento text,
  parentesco text,
  telefone text
);

CREATE TABLE IF NOT EXISTS student_beneficios (
  student_id bigint NOT NULL REFERENCES students(id) ON DELETE CASCADE,
  beneficio text NOT NULL,
  PRIMARY KEY (student_id, beneficio)
);

CREATE TABLE IF NOT EXISTS student_interacao_social (
  student_id bigint NOT NULL REFERENCES students(id) ON DELETE CASCADE,
  item text NOT NULL,
  PRIMARY KEY (student_id, item)
);

CREATE TABLE IF NOT EXISTS student_locais_lazer (
  student_id bigint NOT NULL REFERENCES students(id) ON DELETE CASCADE,
  item text NOT NULL,
  PRIMARY KEY (student_id, item)
);

CREATE TABLE IF NOT EXISTS student_servicos_utilizados (
  student_id bigint NOT NULL REFERENCES students(id) ON DELETE CASCADE,
  item text NOT NULL,
  PRIMARY KEY (student_id, item)
);

CREATE TABLE IF NOT EXISTS student_audit_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id bigint NOT NULL REFERENCES students(id) ON DELETE CASCADE,
  student_name text NOT NULL,
  action text NOT NULL CHECK (action IN ('create', 'update', 'delete')),
  at timestamptz NOT NULL DEFAULT now(),
  by_user_id bigint REFERENCES users(id),
  by_email text NOT NULL,
  changed_fields jsonb
);

CREATE INDEX IF NOT EXISTS idx_student_audit_events_student_id ON student_audit_events (student_id);
CREATE INDEX IF NOT EXISTS idx_student_audit_events_by_email ON student_audit_events (by_email);
CREATE INDEX IF NOT EXISTS idx_student_audit_events_at ON student_audit_events (at DESC);

CREATE OR REPLACE VIEW v_account_student_stats AS
SELECT
  u.id AS user_id,
  u.email,
  u.role,
  u.created_at,
  u.last_login_at,
  COUNT(DISTINCT s.id) FILTER (WHERE s.created_by_email = u.email) AS alunos_adicionados,
  COUNT(ae.id) FILTER (WHERE ae.action = 'update' AND ae.by_email = u.email) AS alteracoes_total,
  COUNT(DISTINCT ae.student_id) FILTER (WHERE ae.action = 'update' AND ae.by_email = u.email) AS alunos_alterados_distintos
FROM users u
LEFT JOIN students s ON s.created_by_email = u.email
LEFT JOIN student_audit_events ae ON ae.by_email = u.email
WHERE u.deleted_at IS NULL
GROUP BY u.id, u.email, u.role, u.created_at, u.last_login_at;
