-- Seed minimo para o banco PostgreSQL do projeto.
-- Este arquivo insere somente 3 estudantes de exemplo.

INSERT INTO users (
  name,
  email,
  role,
  status,
  password_hash,
  created_at,
  last_login_at,
  approved_at,
  deleted_at
)
VALUES (
  'Administrador',
  'adm@sementesdoamanha.com',
  'admin',
  'approved',
  'scrypt:32768:8:1$mock$mock',
  '2026-05-06 09:00:00',
  '2026-05-06 09:00:00',
  '2026-05-06 09:00:00',
  NULL
)
ON CONFLICT (email) DO NOTHING;

INSERT INTO students (
  nome_completo,
  foto_crianca,
  data_nascimento,
  idade,
  naturalidade,
  raca_cor,
  sexo,
  rg,
  cpf,
  nis,
  certidao_termo,
  certidao_folha,
  certidao_livro,
  endereco_cep,
  endereco_logradouro,
  endereco_numero,
  endereco_complemento,
  endereco_bairro,
  endereco_cidade,
  endereco_uf,
  nome_pai,
  nome_mae,
  cras_referencia,
  estado_civil_pais,
  contato_conjuge_nome,
  contato_conjuge_telefone,
  tipo_domicilio,
  renda_familiar,
  beneficio_outros,
  ativo,
  unidade,
  escola_nome,
  escola_serie,
  escola_ano,
  escola_professor,
  escola_periodo,
  historico_escolar,
  ubs_referencia,
  tem_problema_saude,
  problema_saude_descricao,
  tem_restricoes,
  restricoes_descricao,
  usa_medicamentos,
  medicamentos_descricao,
  tem_alergias,
  alergias_descricao,
  acompanhamentos,
  tem_deficiencia,
  deficiencia_descricao,
  tem_supervisao,
  supervisao_descricao,
  atividades_extras,
  termo_responsabilidade,
  autorizacao_imagem,
  autorizacao_saida,
  created_at,
  created_by_user_id,
  created_by_email,
  updated_at,
  updated_by_user_id,
  updated_by_email
)
SELECT
  'Ana Clara Souza',
  '',
  '2016-03-15',
  10,
  'Taboao da Serra/SP',
  'Parda',
  'Feminino',
  '456789123',
  '12345678901',
  '12345678901',
  '1234567',
  '101',
  'AB123',
  '06765000',
  'Rua das Flores',
  '120',
  'Casa 2',
  'Jardim Mirna',
  'Taboao da Serra',
  'SP',
  'Carlos Souza',
  'Fernanda Souza',
  'CRAS Jardim Mirna',
  'Casado(a)',
  'Carlos Souza',
  '11987654321',
  'Alugado',
  'R$ 2.350,00',
  '',
  true,
  'Unidade Mirna',
  'EMEF Monte Alegre',
  '5a serie',
  '5o ano',
  'Juliana Lima',
  'Tarde',
  'Sem ocorrencias relevantes.',
  'UBS Jardim Record',
  false,
  '',
  true,
  'Restricao a corantes artificiais.',
  false,
  '',
  true,
  'Alergia a poeira.',
  'Acompanhamento social no territorio.',
  false,
  '',
  true,
  'Precisa de apoio nas travessias de rua.',
  'Bale e reforco escolar.',
  true,
  true,
  'somente-com-responsavel',
  '2026-05-06 10:00:00',
  (SELECT id FROM users WHERE email = 'adm@sementesdoamanha.com' AND deleted_at IS NULL LIMIT 1),
  'adm@sementesdoamanha.com',
  '2026-05-06 10:00:00',
  (SELECT id FROM users WHERE email = 'adm@sementesdoamanha.com' AND deleted_at IS NULL LIMIT 1),
  'adm@sementesdoamanha.com'
WHERE NOT EXISTS (SELECT 1 FROM students WHERE cpf = '12345678901');

INSERT INTO students (
  nome_completo,
  foto_crianca,
  data_nascimento,
  idade,
  naturalidade,
  raca_cor,
  sexo,
  rg,
  cpf,
  nis,
  certidao_termo,
  certidao_folha,
  certidao_livro,
  endereco_cep,
  endereco_logradouro,
  endereco_numero,
  endereco_complemento,
  endereco_bairro,
  endereco_cidade,
  endereco_uf,
  nome_pai,
  nome_mae,
  cras_referencia,
  estado_civil_pais,
  contato_conjuge_nome,
  contato_conjuge_telefone,
  tipo_domicilio,
  renda_familiar,
  beneficio_outros,
  ativo,
  unidade,
  escola_nome,
  escola_serie,
  escola_ano,
  escola_professor,
  escola_periodo,
  historico_escolar,
  ubs_referencia,
  tem_problema_saude,
  problema_saude_descricao,
  tem_restricoes,
  restricoes_descricao,
  usa_medicamentos,
  medicamentos_descricao,
  tem_alergias,
  alergias_descricao,
  acompanhamentos,
  tem_deficiencia,
  deficiencia_descricao,
  tem_supervisao,
  supervisao_descricao,
  atividades_extras,
  termo_responsabilidade,
  autorizacao_imagem,
  autorizacao_saida,
  created_at,
  created_by_user_id,
  created_by_email,
  updated_at,
  updated_by_user_id,
  updated_by_email
)
SELECT
  'Joao Pedro Lima',
  '',
  '2014-08-21',
  11,
  'Sao Paulo/SP',
  'Branca',
  'Masculino',
  '334455667',
  '23456789012',
  '23456789012',
  '2345678',
  '202',
  'CD456',
  '06766010',
  'Avenida dos Ipes',
  '45',
  'Bloco B',
  'Parque Pinheiros',
  'Taboao da Serra',
  'SP',
  'Rogerio Lima',
  'Patricia Lima',
  'CRAS Parque Pinheiros',
  'Uniao Estavel',
  'Patricia Lima',
  '11981234567',
  'Proprio',
  'R$ 3.100,00',
  'Auxilio transporte escolar',
  true,
  'Unidade Centro',
  'EMEF Machado de Assis',
  '6a serie',
  '6o ano',
  'Ricardo Alves',
  'Manha',
  'Mudou de escola em 2025.',
  'UBS Oliveiras',
  true,
  'Asma leve.',
  false,
  '',
  true,
  'Bombinha quando necessario.',
  false,
  '',
  'Acompanhamento no CAPS infantil.',
  false,
  '',
  false,
  '',
  'Futebol.',
  true,
  false,
  'sim',
  '2026-05-06 10:15:00',
  (SELECT id FROM users WHERE email = 'adm@sementesdoamanha.com' AND deleted_at IS NULL LIMIT 1),
  'adm@sementesdoamanha.com',
  '2026-05-06 10:15:00',
  (SELECT id FROM users WHERE email = 'adm@sementesdoamanha.com' AND deleted_at IS NULL LIMIT 1),
  'adm@sementesdoamanha.com'
WHERE NOT EXISTS (SELECT 1 FROM students WHERE cpf = '23456789012');

INSERT INTO students (
  nome_completo,
  foto_crianca,
  data_nascimento,
  idade,
  naturalidade,
  raca_cor,
  sexo,
  rg,
  cpf,
  nis,
  certidao_termo,
  certidao_folha,
  certidao_livro,
  endereco_cep,
  endereco_logradouro,
  endereco_numero,
  endereco_complemento,
  endereco_bairro,
  endereco_cidade,
  endereco_uf,
  nome_pai,
  nome_mae,
  cras_referencia,
  estado_civil_pais,
  contato_conjuge_nome,
  contato_conjuge_telefone,
  tipo_domicilio,
  renda_familiar,
  beneficio_outros,
  ativo,
  unidade,
  escola_nome,
  escola_serie,
  escola_ano,
  escola_professor,
  escola_periodo,
  historico_escolar,
  ubs_referencia,
  tem_problema_saude,
  problema_saude_descricao,
  tem_restricoes,
  restricoes_descricao,
  usa_medicamentos,
  medicamentos_descricao,
  tem_alergias,
  alergias_descricao,
  acompanhamentos,
  tem_deficiencia,
  deficiencia_descricao,
  tem_supervisao,
  supervisao_descricao,
  atividades_extras,
  termo_responsabilidade,
  autorizacao_imagem,
  autorizacao_saida,
  created_at,
  created_by_user_id,
  created_by_email,
  updated_at,
  updated_by_user_id,
  updated_by_email
)
SELECT
  'Maria Eduarda Santos',
  '',
  '2012-11-02',
  13,
  'Embu das Artes/SP',
  'Preta',
  'Feminino',
  '998877665',
  '34567890123',
  '34567890123',
  '3456789',
  '303',
  'EF789',
  '06767020',
  'Rua Esperanca',
  '300',
  '',
  'Jardim Saint Moritz',
  'Taboao da Serra',
  'SP',
  'Paulo Santos',
  'Luciana Santos',
  'CRAS Saint Moritz',
  'Divorciado(a)',
  'Luciana Santos',
  '11992345678',
  'Cedido',
  'R$ 1.780,00',
  '',
  true,
  'Unidade Sao Judas',
  'EE Professora Zilda Natel',
  '8a serie',
  '8o ano',
  'Marcos Vinicius',
  'Integral',
  'Retornou as aulas apos mudanca de endereco.',
  'UBS Santa Cecilia',
  false,
  '',
  false,
  '',
  false,
  '',
  true,
  'Alergia a camarao.',
  'Atendimento psicossocial eventual.',
  true,
  'Baixa visao no olho esquerdo.',
  true,
  'Necessita apoio no deslocamento noturno.',
  'Oficina de artes e coral.',
  true,
  true,
  'nao',
  '2026-05-06 10:30:00',
  (SELECT id FROM users WHERE email = 'adm@sementesdoamanha.com' AND deleted_at IS NULL LIMIT 1),
  'adm@sementesdoamanha.com',
  '2026-05-06 10:30:00',
  (SELECT id FROM users WHERE email = 'adm@sementesdoamanha.com' AND deleted_at IS NULL LIMIT 1),
  'adm@sementesdoamanha.com'
WHERE NOT EXISTS (SELECT 1 FROM students WHERE cpf = '34567890123');
